_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: bff92912-ad5e-4ec3-9d45-f1b1f1adf656
name: 'Pantheon Build Tools Drupal'
mail: mike.burns@upstatement.com
slogan: 'Drupal 9 on Pantheon via Build Tools'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
